//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdBid
    {
        public int BidId { get; set; }
        public int AdId { get; set; }
        public int BidAmount { get; set; }
        public System.DateTime BidDate { get; set; }
        public bool IsHighestBid { get; set; }
        public bool IsActive { get; set; }
        public string UserToken { get; set; }
        public string UserName { get; set; }
    }
}
