//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IFdbEntities : DbContext
    {
        public IFdbEntities()
            : base("name=IFdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdBid> AdBids { get; set; }
        public DbSet<AdComment> AdComments { get; set; }
        public DbSet<AdReport> AdReports { get; set; }
        public DbSet<Ad> Ads { get; set; }
        public DbSet<AdsDemand> AdsDemands { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CityMasterTable> CityMasterTables { get; set; }
        public DbSet<Locality> Localities { get; set; }
        public DbSet<UserFeedback> UserFeedbacks { get; set; }
        public DbSet<UserNotification> UserNotifications { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WishComment> WishComments { get; set; }
        public DbSet<WishFulfill> WishFulfills { get; set; }
        public DbSet<WishList> WishLists { get; set; }
        public DbSet<WishReport> WishReports { get; set; }
    }
}
