//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public int LocalityId { get; set; }
        public string LocalityName { get; set; }
        public string LocalityCity { get; set; }
        public string LocalityDivision { get; set; }
        public string CreatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
