//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int NotificationId { get; set; }
        public int AdOrWishId { get; set; }
        public bool isFirstBid { get; set; }
        public bool isHigherBid { get; set; }
        public bool isDemand { get; set; }
        public bool isFulfill { get; set; }
        public bool isCommentForAd { get; set; }
        public bool isCommentForWish { get; set; }
        public string UserToken { get; set; }
        public string UserName { get; set; }
        public string UserPhoneNumber { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public bool isRead { get; set; }
        public string VendorName { get; set; }
        public string VendorToken { get; set; }
        public Nullable<bool> isNew { get; set; }
        public bool isDisplayPhoneNumber { get; set; }
    }
}
