//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishId { get; set; }
        public string WishDescription { get; set; }
        public string WishCategory { get; set; }
        public string WishLocality { get; set; }
        public string WishCity { get; set; }
        public string WishImage { get; set; }
        public string UserName { get; set; }
        public string UserPhoneNumber { get; set; }
        public string UserToken { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsReported { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> NoOfFulfill { get; set; }
        public string WishDivision { get; set; }
        public bool isDisplayPhoneNumber { get; set; }
    }
}
