//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishReport
    {
        public int ReportId { get; set; }
        public int WishId { get; set; }
        public string ReportReason { get; set; }
        public System.DateTime ReportDate { get; set; }
        public bool IsActive { get; set; }
        public string UserToken { get; set; }
        public string UserName { get; set; }
    }
}
