//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishFulfill
    {
        public int FulfillId { get; set; }
        public int WishId { get; set; }
        public string UserToken { get; set; }
        public System.DateTime FullfillDate { get; set; }
    }
}
